export const STRINGS = {
  LOGIN_ACCOUNT: "Login Account",
  LOGIN: "Login",
  LOGIN_GOOGLE: "Login with Google",
  LOGIN_FAILED:
    "Login failed! Please recheck the username and password and try again.",
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  SIGN_UP: "Sign up",
  NOW: "now.",
  OR: "or",
  FORGOT_PASSWORD_QUESTION: "Forgot password?",
  PASSWORD: "Password",
  EMAIL: "Email",
  LAST_NAME: "Last name",
  FIRST_NAME: "First name",
  REPEAT_PASSWORD: "Repeat password",
  SIGN_UP_FAILED:
    "Please ensure that the password matches, the email is valid, and all the boxes are completed.",
  ALREADY_HAVE_ACCOUNT: "Already have an account?",
  GO_TO: "Go to",
  PAGE: "page.",
  FORGOT_YOUR_PASSWORD: "Forgot your password",
  RESET_PASSWORD: "Reset password",
  BACK_TO_LOGIN: "Back to login",
  PLEASE_ENTER_YOUR_EMAIL_ADDRESS_YOU_LIKE_YOUR_PASSWORD_INFORMATION_SEND_TO:
    "Please enter the email address you'd like your password resend information send to.",
  GENERIC_ERROR_MESSAGE: "Error",
  ENTER_VALID_EMAIL: "Please enter a valid email.",
  ACCOUNT: "Account",
  PROFILE: "Profile",
  SETTINGS: "Settings",
  LOG_OUT: "Log out",
  FOR_TEAM: "For team",
  PROJECTS: "Projects",
  FREE_DAYS: "Free days",
  BOOK_DESK: "Book a desk",
  BOOK_PARKING: "Book parking lot",
  EFFORTLESSLY_MANAGE_YOUR_TASKS: "Streamline your work, simplify your life",
  DOCUMENT_NOT_FOUND: "Document not found.",
  GENERIG_ERROR_MESSAGE: "Error.",
  EDIT_PROFILE: "Edit profile",
  SAVE: "Save",
  PROFILE_INFO: "Profile info",
  ADD_MEMBERS: "Add members",
  DELETE_PROFILE: "Delete profile",
  SELECT_TYPE_OF_FREE_DAYS: "Select type of free days",
  UNPAID: "Unpaid",
  VACANTION: "Vacantion",
  SICK: "Sick",
  SEND_FREE_DAYS_REQUEST: "Send free days request",
  CLEAR: "Clear",
};
