import { Navbar } from "@/components/Navbar";
import { useAppDispatch, useAppSelector } from "@/core/store";
import { getLoggedUserData } from "@/redux/getLoggedUser/slice";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  const data = {
    email: "string",
  };

  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getLoggedUserData());
  }, [dispatch]);
  const user = useAppSelector((state) => state.loggedUser.user);

  useEffect(() => {
    console.log(user);
  }, [user]);

  return (
    <>
      <Head>
        <title>WorkEase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>Apuca-te de Treaba Simona!!</div>
      <div>OKKK!!</div>
    </>
  );
}
